<Counter>
    texture: None
    start_count: None
    count: self.start_count

    canvas.before:
        Rectangle:
            size: self.size
            pos: self.pos
            texture: self.texture

    Label:
        text: str(root.count)
        color: (120/255, 81/255, 169/255, 1)
        size_hint: (0.2, 0.2)
        pos_hint: {"center_x": 0.5, "center_y": 0.8}
        font_size: (self.width*self.height)**0.5
